# Generated by Django 4.2.16 on 2026-05-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_ky', models.CharField(blank=True, max_length=200, verbose_name='Аталышы (кыр)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_ky', models.TextField(blank=True, verbose_name='Сүрөттөмө (кыр)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена от (сом)')),
                ('price_to', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена до (сом)')),
                ('icon', models.CharField(default='bi-bandaid', help_text='Класс Bootstrap Icons, например: bi-tooth, bi-heart-pulse', max_length=60, verbose_name='Иконка Bootstrap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(default='г. Бишкек', max_length=500, verbose_name='Адрес (рус)')),
                ('address_ky', models.CharField(default='Бишкек ш.', max_length=500, verbose_name='Дарек (кыр)')),
                ('phone', models.CharField(default='+996 (700) 000-000', max_length=50, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, default='info@smile-estetic.kg', max_length=254, verbose_name='Email')),
                ('working_hours_ru', models.CharField(default='Пн–Пт: 9:00–19:00, Сб: 9:00–16:00', max_length=200, verbose_name='Часы работы (рус)')),
                ('working_hours_ky', models.CharField(default='Дүйш–Жума: 9:00–19:00, Ишемби: 9:00–16:00', max_length=200, verbose_name='Иштөө убактысы (кыр)')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp (номер)')),
                ('hero_title_ru', models.CharField(default='Ваша улыбка — наша забота', max_length=200, verbose_name='Заголовок главной (рус)')),
                ('hero_title_ky', models.CharField(default='Сиздин жылмайуу — биздин камкордук', max_length=200, verbose_name='Заголовок главной (кыр)')),
                ('hero_subtitle_ru', models.TextField(default='Профессиональная стоматологическая помощь в Бишкеке. Современное оборудование, опытные врачи.', verbose_name='Подзаголовок главной (рус)')),
                ('hero_subtitle_ky', models.TextField(default='Бишкекте профессионалдуу стоматологиялык жардам. Заманбап жабдуулар, тажрыйбалуу дарыгерлер.', verbose_name='Подзаголовок главной (кыр)')),
                ('about_ru', models.TextField(default='Smile Estetic — современный стоматологический центр, где каждый пациент получает индивидуальный подход и качественное лечение.', verbose_name='О клинике (рус)')),
                ('about_ky', models.TextField(default='Smile Estetic — заманбап стоматологиялык борбор, ар бир бейтап жеке мамиле жана сапаттуу дарылоо алат.', verbose_name='О клинике (кыр)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (рус)')),
                ('name_ky', models.CharField(blank=True, max_length=200, verbose_name='Аты (кыр)')),
                ('specialty_ru', models.CharField(max_length=200, verbose_name='Специальность (рус)')),
                ('specialty_ky', models.CharField(blank=True, max_length=200, verbose_name='Адистиги (кыр)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialists/', verbose_name='Фото')),
                ('bio_ru', models.TextField(blank=True, verbose_name='Биография (рус)')),
                ('bio_ky', models.TextField(blank=True, verbose_name='Өмүр баяны (кыр)')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Опыт (лет)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('text_ru', models.TextField(verbose_name='Отзыв (рус)')),
                ('text_ky', models.TextField(blank=True, verbose_name='Пикир (кыр)')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], default=5, verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Имя пациента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('preferred_date', models.DateField(verbose_name='Желаемая дата')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.service', verbose_name='Услуга')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник / Дүйшөмбү'), (1, 'Вторник / Шейшемби'), (2, 'Среда / Шаршемби'), (3, 'Четверг / Бейшемби'), (4, 'Пятница / Жума'), (5, 'Суббота / Ишемби'), (6, 'Воскресенье / Жекшемби')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['specialist', 'day_of_week'],
                'unique_together': {('specialist', 'day_of_week')},
            },
        ),
    ]
