# Generated by Django 4.2.16 on 2026-05-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Желаемое время'),
        ),
    ]
